#import <Foundation/Foundation.h>

/**
  IQUSDKIdType defines the different types of IDs that are supported by the IQU SDK.
*/
typedef NS_ENUM(NSInteger, IQUSDKIDType) {
  /**
    An id that is generated by SDK and stored in local persistent storage.
  */
  IQUSDKIDTypeSDK = 0,

  /**
    An id that is obtained from Facebook.
  */
  IQUSDKIDTypeFacebook = 1,

  /**
    An id that is obtained from Google+.
  */
  IQUSDKIDTypeGooglePlus = 2,

  /**
    An id that is obtained from Twitter.
  */
  IQUSDKIDTypeTwitter = 3,

  /**
    A custom id
  */
  IQUSDKIDTypeCustom = 4,

  /**
    iOS identifier for vendor
  */
  IQUSDKIDTypeIOSVendor = 5,

  /**
    iOS advertising identifier
  */
  IQUSDKIDTypeIOSAdvertising = 6,
  
  /**
    Not really an ID, contains "1" if ad tracking is allowed.
  */
  IQUSDKIDTypeIOSAdTracking = 7
};
